name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile Java Files
        run: |
          mkdir -p out
          javac -cp ".:src/libs/junit-jupiter-api-5.10.2.jar" -d out $(find src -name "*.java") $(find src/tests -name "*.java")

      - name: Run Unit Tests
        run: |
          java -cp ".:out:src/libs/junit-jupiter-api-5.10.2.jar:src/libs/junit-jupiter-engine-5.10.2.jar:src/libs/junit-platform-console-standalone-1.11.0.jar" org.junit.platform.console.ConsoleLauncher --scan-classpath --classpath out

     